const isElectron = window.api !== undefined;

const getAppHeight = () => {
  if (typeof window !== 'undefined' && /Mobi|Android/i.test(navigator.userAgent)) {
    return `${window.innerHeight}px`;
  }
  return isElectron ? 'calc(100vh - 30px)' : '100vh';
};



export const layoutStyles = {
  appContainer: {
    width: '100vw',
    height: getAppHeight(),
    bg: 'var(--olv-bg)',
    color: 'var(--olv-text)',
    overflow: 'hidden',
    position: 'relative',
    display: 'flex',
    flexDirection: { base: 'column', md: 'row' },
    mt: isElectron ? '30px' : '0',
    isolation: 'isolate',
  },
  sidebar: {
    position: 'relative' as const,
    width: { base: '100%', md: '440px' },
    height: { base: 'auto', md: '100%' },
    bg: 'var(--olv-bg)',
    borderRight: '1px solid',
    borderColor: 'var(--olv-border)',
    overflow: 'hidden',
    flexShrink: 0,
    transition: 'all 0.2s',
  },
  mainContent: {
    flex: 1,
    height: { base: 'calc(100% - 120px)', md: '100%' },
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    width: '100%',
    overflow: 'hidden',
  },
  canvas: {
    position: 'relative',
    width: '100%',
    flex: 1,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
    willChange: 'transform',
  },
  footer: {
    width: '100%',
    height: { base: '100px', md: '116px' },
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'transform',
    position: 'relative',
    zIndex: 1,
  },
  toggleButton: {
    position: 'absolute',
    left: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    height: '60px',
    bg: 'rgba(10, 10, 10, 0.72)',
    color: 'var(--olv-muted)',
    border: '1px solid',
    borderColor: 'var(--olv-border)',
    _hover: { bg: 'rgba(255,255,255,0.06)', color: 'var(--olv-text)' },
    borderLeftRadius: 0,
    borderRightRadius: '8px',
    zIndex: 10,
  },
  canvasHeight: (isFooterCollapsed: boolean) => ({
    height: isFooterCollapsed ? 'calc(100% - 24px)' : 'calc(100% - 120px)',
  }),
  sidebarToggleButton: {
    position: 'absolute',
    left: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    height: '60px',
    bg: 'rgba(10, 10, 10, 0.72)',
    color: 'var(--olv-muted)',
    border: '1px solid',
    borderColor: 'var(--olv-border)',
    borderLeftRadius: 0,
    borderRightRadius: '8px',
    zIndex: 10,
  },
  collapsedFooter: {
    height: { base: '20px', md: '24px' },
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  windowsTitleBar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '30px',
    backgroundColor: 'rgba(10, 10, 10, 0.94)',
    borderBottom: '1px solid',
    borderColor: 'var(--olv-border)',
    paddingX: '10px',
    zIndex: 1000,
    backdropFilter: 'blur(18px)',
    css: { WebkitAppRegion: 'drag' },
  },
  macTitleBar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '30px',
    backgroundColor: 'rgba(10, 10, 10, 0.94)',
    borderBottom: '1px solid',
    borderColor: 'var(--olv-border)',
    zIndex: 1000,
    backdropFilter: 'blur(18px)',
    css: {
      WebkitAppRegion: 'drag',
      '-webkit-user-select': 'none',
    },
  },
  titleBarTitle: {
    fontSize: '12px',
    color: 'var(--olv-muted)',
    fontWeight: '500',
    textAlign: 'center',
  },
  titleBarButtons: {
    display: 'flex',
    gap: '1',
  },
  titleBarButton: {
    size: 'sm',
    variant: 'ghost',
    color: 'var(--olv-muted)',
    borderRadius: '6px',
    css: { WebkitAppRegion: 'no-drag' },
    _hover: { backgroundColor: 'rgba(255,255,255,0.08)', color: 'var(--olv-text)' },
  },
  closeButton: {
    size: 'sm',
    variant: 'ghost',
    color: 'var(--olv-muted)',
    borderRadius: '6px',
    css: { WebkitAppRegion: 'no-drag' },
    _hover: { backgroundColor: 'var(--olv-danger)', color: 'white' },
  },
} as const;
