export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      backgroundColor: 'rgba(10, 10, 10, 0.78)',
      border: '1px solid var(--olv-border)',
      backdropFilter: 'blur(18px)',
      padding: '12px 22px',
      borderRadius: '8px',
      minWidth: '60%',
      maxWidth: '95%',
      boxShadow: '0 18px 48px rgba(0, 0, 0, 0.28)',
    },
    text: {
      color: 'var(--olv-text)',
      fontSize: '1.15rem',
      fontWeight: '500',
      textAlign: 'center',
      lineHeight: '1.4',
      whiteSpace: 'pre-wrap',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      // top: '20px',
      // left: '20px',
      zIndex: 2,
      padding: '7px 12px',
      borderRadius: '999px',
      fontSize: '12px',
      fontWeight: '600',
      color: 'var(--olv-text)',
      border: '1px solid var(--olv-border)',
      backdropFilter: 'blur(18px)',
      boxShadow: '0 12px 40px rgba(0, 0, 0, 0.28)',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      _hover: {
        borderColor: 'var(--olv-border-strong)',
      },
    },
  },
};
